[project]
name = "py-dc"
version = "0.1.0"
description = "python data-camp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.9",
    "matplotlib>=3.10.7",
    "pandas>=2.3.2",
    "plotly>=6.3.1",
    "pycodestyle>=2.14.0",
    "scikit-learn>=1.7.2",
]
