[project]
name = "py-dc"
version = "0.1.0"
description = "python data-camp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.9",
    "pandas>=2.3.2",
    "pycodestyle>=2.14.0",
]
